--- #YAML:1.0
name:                     Acme-CPANAuthors-British
version:                  0.16
abstract:                 We are British CPAN authors.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Acme::CPANAuthors:      0.04
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  Test::More:             0.70
  IO::File:               0

provides:
  Acme::CPANAuthors::British:
    file:     lib/Acme/CPANAuthors/British.pm
    version:  0.16
  Acme::CPANAuthors::British::Companies:
    file:     lib/Acme/CPANAuthors/British/Companies.pm
    version:  0.16
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-British
  repository: http://github.com/barbie/acme-cpanauthors-british

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
