--- #YAML:1.0
name:                     Acme-CPANAuthors-British
version:                  0.07
abstract:                 We are British CPAN authors.
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Acme::CPANAuthors:      0.04
  Test::More:             0.70
  IO::File:               0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
build_requires:
  Test::More:             0.70

provides:
  Acme::CPANAuthors::British:
    file:     lib/Acme/CPANAuthors/British.pm
    version:  0.07
  Acme::CPANAuthors::British::Companies:
    file:     lib/Acme/CPANAuthors/British/Companies.pm
    version:  0.07
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-British
  repository: http://github.com/barbie/acme-cpanauthors-british

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
